const configPricesTypes = {
  START_GET_LIST_CONFIG_PRICES: "START_GET_LIST_CONFIG_PRICES",
  GET_LIST_CONFIG_PRICES_SUCCESS: "GET_LIST_CONFIG_PRICES_SUCCESS",
  GET_LIST_CONFIG_PRICES_FAILURE: "GET_LIST_CONFIG_PRICES_FAILURE",

  START_UPDATE_ONE_CONFIG_PRICES: "START_UPDATE_ONE_CONFIG_PRICES",
  UPDATE_ONE_CONFIG_PRICES_SUCCESS: "UPDATE_ONE_CONFIG_PRICES_SUCCESS",
  UPDATE_ONE_CONFIG_PRICES_FAILURE: "UPDATE_ONE_CONFIG_PRICES_FAILURE",

  START_CREATE_ONE_CONFIG_PRICES: "START_CREATE_ONE_CONFIG_PRICES",
  CREATE_ONE_CONFIG_PRICES_SUCCESS: "CREATE_ONE_CONFIG_PRICES_SUCCESS",
  CREATE_ONE_CONFIG_PRICES_FAILURE: "CREATE_ONE_CONFIG_PRICES_FAILURE",

  START_GET_CONFIG_PRICES_BY_ID: "START_GET_CONFIG_PRICES_BY_ID",
  GET_CONFIG_PRICES_BY_ID_SUCCESS: "GET_CONFIG_PRICES_BY_ID_SUCCESS",
  GET_CONFIG_PRICES_BY_ID_FAILURE: "GET_CONFIG_PRICES_BY_ID_FAILURE",

  START_UPDATE_ONE_CONFIG_PRICES_DETAILS:
    "START_UPDATE_ONE_CONFIG_PRICES_DETAILS",
  UPDATE_ONE_CONFIG_PRICES_DETAILS_SUCCESS:
    "UPDATE_ONE_CONFIG_PRICES_DETAILS_SUCCESS",
  UPDATE_ONE_CONFIG_PRICES_DETAILS_FAILURE:
    "UPDATE_ONE_CONFIG_PRICES_DETAILS_FAILURE",

  START_GET_LIST_CONFIG_PRICES_DETAILS: "START_GET_LIST_CONFIG_PRICES_DETAILS",
  GET_LIST_CONFIG_PRICES_DETAILS_SUCCESS:
    "GET_LIST_CONFIG_PRICES_DETAILS_SUCCESS",
  GET_LIST_CONFIG_PRICES_DETAILS_FAILURE:
    "GET_LIST_CONFIG_PRICES_DETAILS_FAILURE",

  START_CREATE_ONE_CONFIG_PRICES_DETAILS:
    "START_CREATE_ONE_CONFIG_PRICES_DETAILS",
  CREATE_ONE_CONFIG_PRICES_DETAILS_SUCCESS:
    "CREATE_ONE_CONFIG_PRICES_DETAILS_SUCCESS",
  CREATE_ONE_CONFIG_PRICES_DETAILS_FAILURE:
    "CREATE_ONE_CONFIG_PRICES_DETAILS_FAILURE",

  START_UPDATE_ONE_CONFIG_PRICES_APPLYS:
    "START_UPDATE_ONE_CONFIG_PRICES_APPLYS",
  UPDATE_ONE_CONFIG_PRICES_APPLYS_SUCCESS:
    "UPDATE_ONE_CONFIG_PRICES_APPLYS_SUCCESS",
  UPDATE_ONE_CONFIG_PRICES_APPLYS_FAILURE:
    "UPDATE_ONE_CONFIG_PRICES_APPLYS_FAILURE",

  START_GET_LIST_CONFIG_PRICES_APPLYS: "START_GET_LIST_CONFIG_PRICES_APPLYS",
  GET_LIST_CONFIG_PRICES_APPLYS_SUCCESS:
    "GET_LIST_CONFIG_PRICES_APPLYS_SUCCESS",
  GET_LIST_CONFIG_PRICES_APPLYS_FAILURE:
    "GET_LIST_CONFIG_PRICES_APPLYS_FAILURE",

  START_CREATE_ONE_CONFIG_PRICES_APPLYS:
    "START_CREATE_ONE_CONFIG_PRICES_APPLYS",
  CREATE_ONE_CONFIG_PRICES_APPLYS_SUCCESS:
    "CREATE_ONE_CONFIG_PRICES_APPLYS_SUCCESS",
  CREATE_ONE_CONFIG_PRICES_APPLYS_FAILURE:
    "CREATE_ONE_CONFIG_PRICES_APPLYS_FAILURE",
};

export default configPricesTypes;
