const configZonesTypes = {
  START_GET_LIST_CONFIG_ZONES: "START_GET_LIST_CONFIG_ZONES",
  GET_LIST_CONFIG_ZONES_SUCCESS: "GET_LIST_CONFIG_ZONES_SUCCESS",
  GET_LIST_CONFIG_ZONES_FAILURE: "GET_LIST_CONFIG_ZONES_FAILURE",

  START_UPDATE_ONE_CONFIG_ZONES: "START_UPDATE_ONE_CONFIG_ZONES",
  UPDATE_ONE_CONFIG_ZONES_SUCCESS: "UPDATE_ONE_CONFIG_ZONES_SUCCESS",
  UPDATE_ONE_CONFIG_ZONES_FAILURE: "UPDATE_ONE_CONFIG_ZONES_FAILURE",

  START_CREATE_ONE_CONFIG_ZONES: "START_CREATE_ONE_CONFIG_ZONES",
  CREATE_ONE_CONFIG_ZONES_SUCCESS: "CREATE_ONE_CONFIG_ZONES_SUCCESS",
  CREATE_ONE_CONFIG_ZONES_FAILURE: "CREATE_ONE_CONFIG_ZONES_FAILURE",

  START_GET_CONFIG_ZONES_BY_ID: "START_GET_CONFIG_ZONES_BY_ID",
  GET_CONFIG_ZONES_BY_ID_SUCCESS: "GET_CONFIG_ZONES_BY_ID_SUCCESS",
  GET_CONFIG_ZONES_BY_ID_FAILURE: "GET_CONFIG_ZONES_BY_ID_FAILURE",

  START_UPDATE_ONE_CONFIG_ZONES_DETAILS:
    "START_UPDATE_ONE_CONFIG_ZONES_DETAILS",
  UPDATE_ONE_CONFIG_ZONES_DETAILS_SUCCESS:
    "UPDATE_ONE_CONFIG_ZONES_DETAILS_SUCCESS",
  UPDATE_ONE_CONFIG_ZONES_DETAILS_FAILURE:
    "UPDATE_ONE_CONFIG_ZONES_DETAILS_FAILURE",

  START_GET_LIST_CONFIG_ZONES_DETAILS: "START_GET_LIST_CONFIG_ZONES_DETAILS",
  GET_LIST_CONFIG_ZONES_DETAILS_SUCCESS:
    "GET_LIST_CONFIG_ZONES_DETAILS_SUCCESS",
  GET_LIST_CONFIG_ZONES_DETAILS_FAILURE:
    "GET_LIST_CONFIG_ZONES_DETAILS_FAILURE",
};

export default configZonesTypes;
