const CUSTOMERPRICETYPES = {
    START_GET_LIST_CUSTOMER_PRICE: 'START_GET_LIST_CUSTOMER_PRICE',
    GET_LIST_CUSTOMER_PRICE_SUCCESS: 'GET_LIST_CUSTOMER_PRICE_SUCCESS',
    GET_LIST_CUSTOMER_PRICE_FAILURE: 'GET_LIST_CUSTOMER_PRICE_FAILURE',
  
    START_GET_LIST_CUSTOMER_PRICE_BY_ID: 'START_GET_LIST_CUSTOMER_PRICE_BY_ID',
    GET_LIST_CUSTOMER_BY_ID_PRICE_SUCCESS: 'GET_LIST_CUSTOMER_BY_ID_PRICE_SUCCESS',
    GET_LIST_CUSTOMER_BY_ID_PRICE_FAILURE: 'GET_LIST_CUSTOMER_BY_ID_PRICE_FAILURE',
  }
  
  export default CUSTOMERPRICETYPES;