const customerSettingTypes = {
  START_GET_LIST_CUSTOMER_SETTING: "START_GET_LIST_CUSTOMER_SETTING",
  GET_LIST_CUSTOMER_SETTING_SUCCESS: "GET_LIST_CUSTOMER_SETTING_SUCCESS",
  GET_LIST_CUSTOMER_SETTING_FAILURE: "GET_LIST_CUSTOMER_SETTING_FAILURE",

  START_UPDATE_ONE_CUSTOMER_SETTING: "START_UPDATE_ONE_CUSTOMER_SETTING",
  UPDATE_ONE_CUSTOMER_SETTING_SUCCESS: "UPDATE_ONE_CUSTOMER_SETTING_SUCCESS",
  UPDATE_ONE_CUSTOMER_SETTING_FAILURE: "UPDATE_ONE_CUSTOMER_SETTING_FAILURE",

  START_GET_CUSTOMER_SETTING_BY_ID: "START_GET_CUSTOMER_SETTING_BY_ID",
  GET_CUSTOMER_SETTING_BY_ID_SUCCESS: "GET_CUSTOMER_SETTING_BY_ID_SUCCESS",
  GET_CUSTOMER_SETTING_BY_ID_FAILURE: "GET_CUSTOMER_SETTING_BY_ID_FAILURE",

  START_CREATE_CUSTOMER_SETTING: "START_CREATE_CUSTOMER_SETTING",
  CREATE_CUSTOMER_SETTING_SUCCESS: "CREATE_CUSTOMER_SETTING_SUCCESS",
  CREATE_CUSTOMER_SETTING_FAILURE: "CREATE_CUSTOMER_SETTING_FAILURE",
};

export default customerSettingTypes;
