const customerAddressTypes = {

  START_GET_LIST_CUSTOMER_ADDRESS: 'START_GET_LIST_CUSTOMER_ADDRESS',
  GET_LIST_CUSTOMER_ADDRESS_SUCCESS: 'GET_LIST_CUSTOMER_ADDRESS_SUCCESS',
  GET_LIST_CUSTOMER_ADDRESS_FAILURE: 'GET_LIST_CUSTOMER_ADDRESS_FAILURE',

  START_UPDATE_ONE_CUSTOMER_ADDRESS: 'START_UPDATE_ONE_CUSTOMER_ADDRESS',
  UPDATE_ONE_CUSTOMER_ADDRESS_SUCCESS: 'UPDATE_ONE_CUSTOMER_ADDRESS_SUCCESS',
  UPDATE_ONE_CUSTOMER_ADDRESS_FAILURE: 'UPDATE_ONE_CUSTOMER_ADDRESS_FAILURE',

  START_CREATE_ONE_CUSTOMER_ADDRESS: 'START_CREATE_ONE_CUSTOMER_ADDRESS',
  CREATE_ONE_CUSTOMER_ADDRESS_SUCCESS: 'CREATE_ONE_CUSTOMER_ADDRESS_SUCCESS',
  CREATE_ONE_CUSTOMER_ADDRESS_FAILURE: 'CREATE_ONE_CUSTOMER_ADDRESS_FAILURE',

  START_GET_CUSTOMER_ADDRESS_BY_ID: 'START_GET_CUSTOMER_ADDRESS_BY_ID',
  GET_CUSTOMER_ADDRESS_BY_ID_SUCCESS: 'GET_CUSTOMER_ADDRESS_BY_ID_SUCCESS',
  GET_CUSTOMER_ADDRESS_BY_ID_FAILURE: 'GET_CUSTOMER_ADDRESS_BY_ID_FAILURE',

}

export default customerAddressTypes;