const exportTypes = {
  START_EXPORT_TEMPLATE: 'START_EXPORT_TEMPLATE',
  GET_EXPORT_TEMPLATE_SUCCESS: 'GET_EXPORT_TEMPLATE_SUCCESS',
  GET_EXPORT_TEMPLATE_FAILURE: 'GET_EXPORT_TEMPLATE_FAILURE',
  
  START_LINK_DOWNLOAD: 'START_LINK_DOWNLOAD',
  GET_LINK_DOWNLOAD_SUCCESS: 'GET_LINK_DOWNLOAD_SUCCESS',
  GET_LINK_DOWNLOAD_FAILURE: 'GET_LINK_DOWNLOAD_FAILURE',
}

export default exportTypes;