const masterDataTypes = {
  // danh sách thành phố
  START_GET_LIST_PROVINCE: 'START_GET_LIST_PROVINCE',
  GET_LIST_PROVINCE_SUCCESS: 'GET_LIST_PROVINCE_SUCCESS',
  GET_LIST_PROVINCE_FAILURE: 'GET_LIST_PROVINCE_FAILURE',

  // danh sách quận huyện
  START_GET_LIST_DISTRICT: 'START_GET_LIST_DISTRICT',
  GET_LIST_DISTRICT_SUCCESS: 'GET_LIST_DISTRICT_SUCCESS',
  GET_LIST_DISTRICT_FAILURE: 'GET_LIST_DISTRICT_FAILURE',
  
  // danh sách phường xã
  START_GET_LIST_WARD: 'START_GET_LIST_WARD',
  GET_LIST_WARD_SUCCESS: 'GET_LIST_WARD_SUCCESS',
  GET_LIST_WARD_FAILURE: 'GET_LIST_WARD_FAILURE',

  // danh sách quyền
  START_GET_LIST_ROLE: 'START_GET_LIST_ROLE',
  GET_LIST_ROLE_SUCCESS: 'GET_LIST_ROLE_SUCCESS',
  GET_LIST_ROLE_FAILURE: 'GET_LIST_ROLE_FAILURE',

  // danh sách ngân hàng
  START_GET_LIST_BANK: 'START_GET_LIST_BANK',
  GET_LIST_BANK_SUCCESS: 'GET_LIST_BANK_SUCCESS',
  GET_LIST_BANK_FAILURE: 'GET_LIST_BANK_FAILURE',

  // danh sách chi nhánh ngân hàng
  START_GET_LIST_BRANCH_BANK: 'START_GET_LIST_BRANCH_BANK',
  GET_LIST_BRANCH_BANK_SUCCESS: 'GET_LIST_BRANCH_BANK_SUCCESS',
  GET_LIST_BRANCH_BANK_FAILURE: 'GET_LIST_BRANCH_BANK_FAILURE',
}

export default masterDataTypes;