const ordersTypes = {
  START_GET_LIST_ORDERS: "START_GET_LIST_ORDERS",
  GET_LIST_ORDERS_SUCCESS: "GET_LIST_ORDERS_SUCCESS",
  GET_LIST_ORDERS_FAILURE: "GET_LIST_ORDERS_FAILURE",

  START_UPDATE_ONE_ORDERS: "START_UPDATE_ONE_ORDERS",
  UPDATE_ONE_ORDERS_SUCCESS: "UPDATE_ONE_ORDERS_SUCCESS",
  UPDATE_ONE_ORDERS_FAILURE: "UPDATE_ONE_ORDERS_FAILURE",

  START_CREATE_ONE_ORDERS: "START_CREATE_ONE_ORDERS",
  CREATE_ONE_ORDERS_SUCCESS: "CREATE_ONE_ORDERS_SUCCESS",
  CREATE_ONE_ORDERS_FAILURE: "CREATE_ONE_ORDERS_FAILURE",

  START_GET_ORDERS_BY_ID: "START_GET_ORDERS_BY_ID",
  GET_ORDERS_BY_ID_SUCCESS: "GET_ORDERS_BY_ID_SUCCESS",
  GET_ORDERS_BY_ID_FAILURE: "GET_ORDERS_BY_ID_FAILURE",

  START_CHANGE_STATUS_BILLS: "START_CHANGE_STATUS_BILLS",
  CHANGE_STATUS_BILLS_SUCCESS: "CHANGE_STATUS_BILLS_SUCCESS",
  CHANGE_STATUS_BILLS_FAILURE: "CHANGE_STATUS_BILLS_FAILURE",

  START_CREATE_ORDERS_BY_FILE: "START_CREATE_ORDERS_BY_FILE",
  CREATE_ORDERS_BY_FILE_SUCCESS: "CREATE_ORDERS_BY_FILE_SUCCESS",
  CREATE_ORDERS_BY_FILE_FAILURE: "CREATE_ORDERS_BY_FILE_FAILURE",

  START_GET_LIST_DELIVERY_BILL: "START_GET_LIST_DELIVERY_BILL",
  GET_LIST_DELIVERY_BILL_SUCCESS: "GET_LIST_DELIVERY_BILL_SUCCESS",
  GET_LIST_DELIVERY_BILL_FAILURE: "GET_LIST_DELIVERY_BILL_FAILURE",

  START_GET_DELIVERY_BILL_BY_ID: "START_GET_DELIVERY_BY_ID",
  GET_DELIVERY_BILL_BY_ID_SUCCESS: "GET_DELIVERY_BILL_BY_ID_SUCCESS",
  GET_DELIVERY_BILL_BY_ID_FAILURE: "GET_DELIVERY_BILL_BY_ID_FAILURE",

  START_CREATE_DELIVERY_BILL: "START_CREATE_DELIVERY_BILL",
  CREATE_DELIVERY_BILL_SUCCESS: "CREATE_DELIVERY_BILL_SUCCESS",
  CREATE_DELIVERY_BILL_FAILURE: "CREATE_DELIVERY_BILL_FAILURE",

  START_UPDATE_DELIVERY_BILL: "START_UPDATE_DELIVERY_BILL",
  UPDATE_DELIVERY_BILL_SUCCESS: "UPDATE_DELIVERY_BILL_SUCCESS",
  UPDATE_DELIVERY_BILL_FAILURE: "UPDATE_DELIVERY_BILL_FAILURE",

  START_CREATE_ORDERS_ARRAY_BY_FILE: "START_CREATE_ORDERS_ARRAY_BY_FILE",
  CREATE_ORDERS_ARRAY_BY_FILE_SUCCESS: "CREATE_ORDERS_ARRAY_BY_FILE_SUCCESS",
  CREATE_ORDERS_ARRAY_BY_FILE_FAILURE: "CREATE_ORDERS_ARRAY_BY_FILE_FAILURE",
//list-of-debt
  START_GET_LIST_OF_DEBT: "START_GET_LIST_OF_DEBT",
  GET_LIST_OF_DEBT_SUCCESS: "GET_LIST_OF_DEBT_SUCCESS",
  GET_LIST_OF_DEBT_FAILURE: "GET_LIST_OF_DEBT_FAILURE",
//package-debt-list
START_CREATE_LIST_OF_DEBT: "START_CREATE_LIST_OF_DEBT",
CREATE_LIST_OF_DEBT_SUCCESS: "CREATE_LIST_OF_DEBT_SUCCESS",
CREATE_LIST_OF_DEBT_FAILURE: "CREATE_LIST_OF_DEBT_FAILURE",

//get-package-debt-list
START_GET_PAKAGE_DEBT_LIST: "START_GET_PAKAGE_DEBT_LIST",
GET_PAKAGE_DEBT_LIST_SUCCESS: "GET_PAKAGE_DEBT_LIST_SUCCESS",
GET_PAKAGE_DEBT_LIST_FAILURE: "GET_PAKAGE_DEBT_LIST_FAILURE",
//get-package-debt-list-by-id
START_GET_PAKAGE_DEBT_LIST_BY_ID: "START_GET_PAKAGE_DEBT_LIST_BY_ID",
GET_PAKAGE_DEBT_LIST_BY_ID_SUCCESS: "GET_PAKAGE_DEBT_LIST_BY_ID_SUCCESS",
GET_PAKAGE_DEBT_LIST_BY_ID_FAILURE: "GET_PAKAGE_DEBT_LIST_BY_ID_FAILURE",
//get-complete-package-debt-list
START_COMPLETE_PAKAGE_DEBT_LIST: "START_COMPLETE_PAKAGE_DEBT_LIST",
COMPLETE_PAKAGE_DEBT_LIST_SUCCESS: "COMPLETE_PAKAGE_DEBT_LIST_SUCCESS",
COMPLETE_PAKAGE_DEBT_LIST_FAILURE: "COMPLETE_PAKAGE_DEBT_LIST_FAILURE",
//get-complete-package-debt-list
START_COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_BY_ID: "START_COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_BY_ID",
COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_SUCCESS_BY_ID: "COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_SUCCESS_BY_ID",
COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_FAILURE_BY_ID: "COMPLETE_OR_DELETE_PAKAGE_DEBT_LIST_FAILURE_BY_ID",
//export file excel
START_EXPORT_EXCEL_PACKAGE_DEBT_LIST: "START_EXPORT_EXCEL_PACKAGE_DEBT_LIST",
EXPORT_EXCEL_PACKAGE_DEBT_LIST_SUCCESS: "EXPORT_EXCEL_PACKAGE_DEBT_LIST_SUCCESS",
EXPORT_EXCEL_PACKAGE_DEBT_LIST_FAILURE: "EXPORT_EXCEL_PACKAGE_DEBT_LIST_FAILURE",
//export debt list detail file excel
START_EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL: "START_EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL",
EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL_SUCCESS: "EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL_SUCCESS",
EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL_FAILURE: "EXPORT_EXCEL_PACKAGE_DEBT_LIST_DETAIL_FAILURE",
};

export default ordersTypes;
