const packageTypes = {
  START_GET_LIST_PACKAGE: "START_GET_LIST_PACKAGE",
  GET_LIST_PACKAGE_SUCCESS: "GET_LIST_PACKAGE_SUCCESS",
  GET_LIST_PACKAGE_FAILURE: "GET_LIST_PACKAGE_FAILURE",

  START_GET_LIST_BILL_PACKAGE: "START_GET_LIST_BILL_PACKAGE",
  GET_LIST_BILL_PACKAGE_SUCCESS: "GET_LIST_BILL_PACKAGE_SUCCESS",
  GET_LIST_BILL_PACKAGE_FAILURE: "GET_LIST_BILL_PACKAGE_FAILURE",

  START_CREATE_PACKAGE: "START_CREATE_PACKAGE",
  CREATE_PACKAGE_SUCCESS: "CREATE_PACKAGE_SUCCESS",
  CREATE_PACKAGE_FAILURE: "CREATE_PACKAGE_FAILURE",

  START_CHANGE_STATUS_PACKAGE: "START_CHANGE_STATUS_PACKAGE",
  CHANGE_STATUS_PACKAGE_SUCCESS: "CHANGE_STATUS_PACKAGE_SUCCESS",
  CHANGE_STATUS_PACKAGE_FAILURE: "CHANGE_STATUS_PACKAGE_FAILURE",

  START_CHANGE_STATUS_LIST_DELIVERY: "START_CHANGE_STATUS_LIST_DELIVERY",
  CHANGE_STATUS_LIST_DELIVERY_SUCCESS: "CHANGE_STATUS_LIST_DELIVERY_SUCCESS",
  CHANGE_STATUS_LIST_DELIVERY_FAILURE: "CHANGE_STATUS_LIST_DELIVERY_FAILURE",

  START_CHANGE_STATUS_BILL_IN_DELIVERY: "START_CHANGE_STATUS_BILL_IN_DELIVERY",
  CHANGE_STATUS_BILL_IN_DELIVERY_SUCCESS:
    "CHANGE_STATUS_BILL_IN_DELIVERY_SUCCESS",
  CHANGE_STATUS_BILL_IN_DELIVERY_FAILURE:
    "CHANGE_STATUS_BILL_IN_DELIVERY_FAILURE",

  START_EXPORT_BILL_DELIVERY: "START_EXPORT_BILL_DELIVERY",
  EXPORT_BILL_DELIVREY_SUCCESS: "EXPORT_BILL_DELIVREY_SUCCESS",
  EXPORT_BILL_DELIVREY_FAILURE: "EXPORT_BILL_DELIVREY_FAILURE",

  START_EXPORT_LIST_BILL: "START_EXPORT_LIST_BILL",
  EXPORT_LIST_BILL_SUCCESS: "EXPORT_LIST_BILL_SUCCESS",
  EXPORT_LIST_BILL_FAILURE: "EXPORT_LIST_BILL_FAILURE",
};

export default packageTypes;
