const reasonTypes = {
    START_GET_LIST_REASON: "START_GET_LIST_REASON",
    GET_LIST_REASON_SUCCESS: "GET_LIST_REASON_SUCCESS",
    GET_LIST_REASON_FAILURE: "GET_LIST_REASON_FAILURE",
  
    START_CREATE_ONE_REASON: "START_CREATE_ONE_REASON",
    CREATE_ONE_REASON_SUCCESS: "CREATE_ONE_REASON_SUCCESS",
    CREATE_ONE_REASON_FAILURE: "CREATE_ONE_REASON_FAILURE",
  
    START_UPDATE_ONE_REASON: "START_UPDATE_ONE_REASON",
    UPDATE_ONE_REASON_SUCCESS: "UPDATE_ONE_REASON_SUCCESS",
    UPDATE_ONE_REASON_FAILURE: "UPDATE_ONE_REASON_FAILURE",
  
    START_GET_REASON_BY_ID: 'START_GET_REASON_BY_ID',
    GET_REASON_BY_ID_SUCCESS: 'GET_REASON_BY_ID_SUCCESS',
    GET_REASON_BY_ID_FAILURE: 'GET_REASON_BY_ID_FAILURE',
  };
  
  export default reasonTypes;
  