const routingAreaTypes = {
    START_GET_LIST_ROUTING_AREA: "START_GET_LIST_ROUTING_AREA",
    GET_LIST_ROUTING_AREA_SUCCESS: "GET_LIST_ROUTING_AREA_SUCCESS",
    GET_LIST_ROUTING_AREA_FAILURE: "GET_LIST_ROUTING_AREA_FAILURE",
  
    START_CREATE_ONE_ROUTING_AREA: "START_CREATE_ONE_ROUTING_AREA",
    CREATE_ONE_ROUTING_AREA_SUCCESS: "CREATE_ONE_ROUTING_AREA_SUCCESS",
    CREATE_ONE_ROUTING_AREA_FAILURE: "CREATE_ONE_ROUTING_AREA_FAILURE",
  
    START_UPDATE_ONE_ROUTING_AREA: "START_UPDATE_ONE_ROUTING_AREA",
    UPDATE_ONE_ROUTING_AREA_SUCCESS: "UPDATE_ONE_ROUTING_AREA_SUCCESS",
    UPDATE_ONE_ROUTING_AREA_FAILURE: "UPDATE_ONE_ROUTING_AREA_FAILURE",
  };
  
  export default routingAreaTypes;
  