const routingsTypes = {
  START_GET_LIST_ROUTINGS: "START_GET_LIST_ROUTINGS",
  GET_LIST_ROUTINGS_SUCCESS: "GET_LIST_ROUTINGS_SUCCESS",
  GET_LIST_ROUTINGS_FAILURE: "GET_LIST_ROUTINGS_FAILURE",

  START_CREATE_ONE_ROUTING: "START_CREATE_ONE_ROUTING",
  CREATE_ONE_ROUTING_SUCCESS: "CREATE_ONE_ROUTING_SUCCESS",
  CREATE_ONE_ROUTING_FAILURE: "CREATE_ONE_ROUTING_FAILURE",

  START_UPDATE_ONE_ROUTING: "START_UPDATE_ONE_ROUTING",
  UPDATE_ONE_ROUTING_SUCCESS: "UPDATE_ONE_ROUTING_SUCCESS",
  UPDATE_ONE_ROUTING_FAILURE: "UPDATE_ONE_ROUTING_FAILURE",

  START_GET_ROUTING_BY_ID: 'START_GET_ROUTING_BY_ID',
  GET_ROUTING_BY_ID_SUCCESS: 'GET_ROUTING_BY_ID_SUCCESS',
  GET_ROUTING_BY_ID_FAILURE: 'GET_ROUTING_BY_ID_FAILURE',
};

export default routingsTypes;
