const supplierTypes = {

    START_GET_LIST_SUPPLIER: 'START_GET_LIST_SUPPLIER',
    GET_LIST_SUPPLIER_SUCCESS: 'GET_LIST_SUPPLIER_SUCCESS',
    GET_LIST_SUPPLIER_FAILURE: 'GET_LIST_SUPPLIER_FAILURE',
  
    START_UPDATE_ONE_SUPPLIER: 'START_UPDATE_ONE_SUPPLIER',
    UPDATE_ONE_SUPPLIER_SUCCESS: 'UPDATE_ONE_SUPPLIER_SUCCESS',
    UPDATE_ONE_SUPPLIER_FAILURE: 'UPDATE_ONE_SUPPLIER_FAILURE',
  
    START_CREATE_ONE_SUPPLIER: 'START_CREATE_ONE_SUPPLIER',
    CREATE_ONE_SUPPLIER_SUCCESS: 'CREATE_ONE_SUPPLIER_SUCCESS',
    CREATE_ONE_SUPPLIER_FAILURE: 'CREATE_ONE_SUPPLIER_FAILURE',
  
    START_GET_SUPPLIER_BY_ID: 'START_GET_SUPPLIER_BY_ID',
    GET_SUPPLIER_BY_ID_SUCCESS: 'GET_SUPPLIER_BY_ID_SUCCESS',
    GET_SUPPLIER_BY_ID_FAILURE: 'GET_SUPPLIER_BY_ID_FAILURE',
  
  }
  
  export default supplierTypes;