const TRAINSTYPES = {
    START_GET_LIST_TRAINS: 'START_GET_LIST_TRAINS',
    GET_LIST_TRAINS_SUCCESS: 'GET_LIST_TRAINS_SUCCESS',
    GET_LIST_TRAINS_FAILURE: 'GET_LIST_TRAINS_FAILURE',
  
    START_CREATE_TRAINS: 'START_CREATE_TRAINS',
    CREATE_TRAINS_SUCCESS: 'CREATE_TRAINS_SUCCESS',
    CREATE_TRAINS_FAILURE: 'CREATE_TRAINS_FAILURE',
  
    START_UPDATE_TRAINS: 'START_UPDATE_TRAINS',
    UPDATE_TRAINS_SUCCESS: 'UPDATE_TRAINS_SUCCESS',
    UPDATE_TRAINS_FAILURE: 'UPDATE_TRAINS_FAILURE',
  }
  
  export default TRAINSTYPES;