const userTypes = {

  START_GET_LIST_USER_SYSTEM: 'START_GET_LIST_USER_SYSTEM',
  GET_LIST_USER_SYSTEM_SUCCESS: 'GET_LIST_USER_SYSTEM_SUCCESS',
  GET_LIST_USER_SYSTEM_FAILURE: 'GET_LIST_USER_SYSTEM_FAILURE',

  START_UPDATE_ONE_USER_SYSTEM: 'START_UPDATE_ONE_USER_SYSTEM',
  UPDATE_ONE_USER_SYSTEM_SUCCESS: 'UPDATE_ONE_USER_SYSTEM_SUCCESS',
  UPDATE_ONE_USER_SYSTEM_FAILURE: 'UPDATE_ONE_USER_SYSTEM_FAILURE',

  START_CHANGE_PASSWORD_BY_USER: 'START_CHANGE_PASSWORD_BY_USER',
  UPDATE_CHANGE_PASSWORD_BY_USER_SUCCESS: 'UPDATE_CHANGE_PASSWORD_BY_USER_SUCCESS',
  UPDATE_CHANGE_PASSWORD_BY_USER_FAILURE: 'UPDATE_CHANGE_PASSWORD_BY_USER_FAILURE',

  START_CREATE_ONE_USER_SYSTEM: 'START_CREATE_ONE_USER_SYSTEM',
  CREATE_ONE_USER_SYSTEM_SUCCESS: 'CREATE_ONE_USER_SYSTEM_SUCCESS',
  CREATE_ONE_USER_SYSTEM_FAILURE: 'CREATE_ONE_USER_SYSTEM_FAILURE',

  START_GET_USER_SYSTEM_BY_ID: 'START_GET_USER_SYSTEM_BY_ID',
  GET_USER_SYSTEM_BY_ID_SUCCESS: 'GET_USER_SYSTEM_BY_ID_SUCCESS',
  GET_USER_SYSTEM_BY_ID_FAILURE: 'GET_USER_SYSTEM_BY_ID_FAILURE',

  START_GET_LIST_USER_GROUPS: 'START_GET_LIST_USER_GROUPS',
  GET_LIST_USER_GROUPS_SUCCESS: 'GET_LIST_USER_GROUPS_SUCCESS',
  GET_LIST_USER_GROUPS_FAILURE: 'GET_LIST_USER_GROUPS_FAILURE',

  START_GET_USER_GROUPS_BY_ID: 'START_GET_USER_GROUPS_BY_ID',
  GET_USER_GROUPS_BY_ID_SUCCESS: 'GET_USER_GROUPS_BY_ID_SUCCESS',
  GET_USER_GROUPS_BY_ID_FAILURE: 'GET_USER_GROUPS_BY_ID_FAILURE',

  START_CREATE_ONE_USER_GROUPS: 'START_CREATE_ONE_USER_GROUPS',
  CREATE_ONE_USER_GROUPS_SUCCESS: 'CREATE_ONE_USER_GROUPS_SUCCESS',
  CREATE_ONE_USER_GROUPS_FAILURE: 'CREATE_ONE_USER_GROUPS_FAILURE',

  START_UPDATE_ONE_USER_GROUPS: 'START_UPDATE_ONE_USER_GROUPS',
  UPDATE_ONE_USER_GROUPS_SUCCESS: 'UPDATE_ONE_USER_GROUPS_SUCCESS',
  UPDATE_ONE_USER_GROUPS_FAILURE: 'UPDATE_ONE_USER_GROUPS_FAILURE',

  START_GET_LIST_USER_GROUPS_PRIVILEGE: 'START_GET_LIST_USER_GROUPS_PRIVILEGE',
  GET_LIST_USER_GROUPS_PRIVILEGE_SUCCESS: 'GET_LIST_USER_GROUPS_PRIVILEGE_SUCCESS',
  GET_LIST_USER_GROUPS_PRIVILEGE_FAILURE: 'GET_LIST_USER_GROUPS_PRIVILEGE_FAILURE',

}

export default userTypes;