const VERHIXLESTYPES = {
  START_GET_LIST_VERHICLE: 'START_GET_LIST_VERHICLE',
  GET_LIST_VERHICLE_SUCCESS: 'GET_LIST_VERHICLE_SUCCESS',
  GET_LIST_VERHICLE_FAILURE: 'GET_LIST_VERHICLE_FAILURE',

  START_CREATE_VERHICLE: 'START_CREATE_VERHICLE',
  CREATE_VERHICLE_SUCCESS: 'CREATE_VERHICLE_SUCCESS',
  CREATE_VERHICLE_FAILURE: 'CREATE_VERHICLE_FAILURE',

  START_UPDATE_VERHICLE: 'START_UPDATE_VERHICLE',
  UPDATE_VERHICLE_SUCCESS: 'UPDATE_VERHICLE_SUCCESS',
  UPDATE_VERHICLE_FAILURE: 'UPDATE_VERHICLE_FAILURE',
}

export default VERHIXLESTYPES;