const warehouseTypes = {

  START_GET_LIST_WAREHOUSE: 'START_GET_LIST_WAREHOUSE',
  GET_LIST_WAREHOUSE_SUCCESS: 'GET_LIST_WAREHOUSE_SUCCESS',
  GET_LIST_WAREHOUSE_FAILURE: 'GET_LIST_WAREHOUSE_FAILURE',

  START_UPDATE_ONE_WAREHOUSE: 'START_UPDATE_ONE_WAREHOUSE',
  UPDATE_ONE_WAREHOUSE_SUCCESS: 'UPDATE_ONE_WAREHOUSE_SUCCESS',
  UPDATE_ONE_WAREHOUSE_FAILURE: 'UPDATE_ONE_WAREHOUSE_FAILURE',

  START_CREATE_ONE_WAREHOUSE: 'START_CREATE_ONE_WAREHOUSE',
  CREATE_ONE_WAREHOUSE_SUCCESS: 'CREATE_ONE_WAREHOUSE_SUCCESS',
  CREATE_ONE_WAREHOUSE_FAILURE: 'CREATE_ONE_WAREHOUSE_FAILURE',

  START_GET_WAREHOUSE_BY_ID: 'START_GET_WAREHOUSE_BY_ID',
  GET_WAREHOUSE_BY_ID_SUCCESS: 'GET_WAREHOUSE_BY_ID_SUCCESS',
  GET_WAREHOUSE_BY_ID_FAILURE: 'GET_WAREHOUSE_BY_ID_FAILURE',

}

export default warehouseTypes;