const warehouseUsersTypes = {
  START_GET_LIST_WAREHOUSE_USER: "START_GET_LIST_WAREHOUSE_USER",
  GET_LIST_WAREHOUSE_USER_SUCCESS: "GET_LIST_WAREHOUSE_USER_SUCCESS",
  GET_LIST_WAREHOUSE_USER_FAILURE: "GET_LIST_WAREHOUSE_USER_FAILURE",

  START_CREATE_ONE_WAREHOUSE_USER: "START_CREATE_ONE_WAREHOUSE_USER",
  CREATE_ONE_WAREHOUSE_USER_SUCCESS: "CREATE_ONE_WAREHOUSE_USER_SUCCESS",
  CREATE_ONE_WAREHOUSE_USER_FAILURE: "CREATE_ONE_WAREHOUSE_USER_FAILURE",

  START_UPDATE_ONE_WAREHOUSE_USER: "START_UPDATE_ONE_WAREHOUSE_USER",
  UPDATE_ONE_WAREHOUSE_USER_SUCCESS: "UPDATE_ONE_WAREHOUSE_USER_SUCCESS",
  UPDATE_ONE_WAREHOUSE_USER_FAILURE: "UPDATE_ONE_WAREHOUSE_USER_FAILURE",
};

export default warehouseUsersTypes;
